platform :ios, '9.0'
use_frameworks!

target 'LoadAlertView' do
     pod 'TYPagerController'
     pod 'UINavigation-SXFixSpace'
     pod 'KafkaRefresh'
     pod 'SDWebImage'
     pod 'MBProgressHUD'
     pod 'TZImagePickerController'
end
